### ISSUE TITLE
Fix layout and add search bar

### ISSUE THREAD

**Issue by vkolova** [vkolova/notum#2]
Fixe layout and add searchbar to every page that has shows on it without breaking the scroll and putting it over the page content.

**Comment by PallaviDas07** [comment]
Can you please elaborate about the layout fixes?@vkolova

**Comment by vkolova** [comment]
Yes, okay... I currently have a search bar in the Home component, and it looks in place (probably because it's the only thing that is in the component). But when I add the search in other components, where I need it, things like this happen: ![bugz](https://user-images.githubusercontent.com/5569382/31314604-0cc840fc-ac0d-11e7-8370-382d310e930f.png)
Unfortunately, I'm not that good with Flexbox and I can't figure out what exactly is wrong, so the `shows-container` is on top of the search bar. I just need it to be a after the search, and be scrollable, without making the whole `view-wrapper` scrollable.
