### ISSUE TITLE
Cannot find module './config' in server.js line 6

### ISSUE THREAD

**Issue by darrylsepeda** [vkolova/notum#5]
Hi, I tried to clone your repo to my local, but when I run in server folder I got an error about cannot find module './config' https://github.com/vkolova/notum/blob/324b60c5fddb4cef4259e45ba66a61bef8a13feb/server/server.js#L6

I already check to your folder, but there is no config.js. Can you explain what is that?

**Comment by vkolova** [comment]
It's a file with the database url

**Comment by darrylsepeda** [comment]
I think you should give a proper documentation of how to run this app locally.
I want to bugfix your issue, but can't run the app.
Can you explain more?

**Comment by AhsanAyaz** [comment]
+1 
Facing the same error.
Looks like the `.config` module is missing

**Comment by vkolova** [comment]
Sorry for the delay, guys. I added info about what should be in that file to run the project.

**Comment by AhsanAyaz** [comment]
@vkolova I think we should have the `.config` file in the repo, and then we'll add it to .gitignore so any private changes are not pushed.

**Comment by AhsanAyaz** [comment]
In fact, it is fine as it is now. Lol 👍
